version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'data'
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3 and invalidating CloudFront distribution...
      # Add your S3 deployment command here if it's not elsewhere
      # e.g., aws s3 sync build/ s3://your-bucket-name/ --delete
      - aws cloudfront create-invalidation --distribution-id E26W502HARIIZ0 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: './build'
  #discard-paths: yes